nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: ['http://localhost:3000']  # Adres Twojej aplikacji React
        allow_headers: ['Content-Type', 'Authorization']  # Dopuszczalne nagłówki
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE']  # Dozwolone metody HTTP
        expose_headers: []
        max_age: 3600
    paths:
        '^/api/': ~  # Zezwalaj na CORS tylko na ścieżce API
